apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: cbci build actions
inputs:
  url:  # id of input
    description: 'cbci url'
    required: true
  username:  # id of input
    description: 'username'
    required: true
  token:  # id of input
    description: 'token or API token'
    required: true
  job-name:  # id of input
    description: 'job name'
    required: true
  test-type:  # id of input
    description: 'test type'
    default: ''
  test-result-location:  # id of input
    description: 'test result location'
    default: ''
  parameters:  # id of input
    description: 'parameters'
    default: '{}'
  
runs:
  using: composite
  steps:
    - id: invoke-cbci-job
      name: invoke-cbci-job
      uses: docker://public.ecr.aws/l7o7z1g8/actions/cbci-actions:main-1d2a1b6772a56ba333c206b1049e14e1a0d2e931
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"CBCI","username":"${{ inputs.username }}","token":"${{ inputs.token }}","jobName":"${{ inputs.job-name }}","testType":"${{ inputs.test-type }}","fileName":"${{ inputs.test-result-location }}","parameters":${{ inputs.parameters }},"commitId":"${{ cloudbees.scm.sha }}"}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./cbci_actions_app invoke -b $CONFIG_JSON
