= CloudBees action: Run a CloudBees CI job

Use this action to trigger a CloudBees CI job. 
To learn more, refer to the link:https://docs.cloudbees.com/docs/cloudbees-ci/latest/[CloudBees CI documentation].

== Inputs

[cols="1a,1a,1a,4a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `url`
| String
| Yes
| The CloudBees CI server URL.

| `username`
| String
| Yes
| The CloudBees CI username.

| `token`
| String
| Yes
| The CloudBees CI token.

| `job-name`
| String
| Yes
| The CloudBees CI job name.

| `test-type`
| String
| No
| Specifies the test type for generating a job test report.
Supported test types are JUnit (`junit`), TestNG (`testng`) and GO (go).

| `test-result-location`
| String
| No
| Specifies the test report file location.
Accepts pattern matching, such as `my-dir/*/my-file`.

| `parameters`
| JSON string
| No
| Any additional CloudBees CI parameters, formatted as JSON data in key/value pairs.
|===

== Outputs

[cols="2a,1a,1a,3a",options="header"]
.Output details
|===

| Output name
| Data type
| Required?
| Description

| `cbci_output`
| String
| No
| A JSON string containing the output key/values exposed by the invoked CloudBees CI pipeline.^<<footnote,[1]>>^


|===

[#footnote]
^[1]^ You must parse each output parameter in the following format:

`fromJSON(steps.<STEP-ID>.outputs.cbci_output).<OUTPUT_PARAMETER>`

Replace `<STEP_ID>` with your step ID, and `<OUTPUT_PARAMETER>` with your parameter.

|===

== Usage examples

In your YAML file, add:

[source,yaml]
----
jobs:
  my-cbci-job:
    steps:
    - name: Run a CloudBees CI job
      uses: cloudbees-io/cbci-run-job@v2
      with:
        url: ${{ vars.CBCI_URL }}
        username: ${{ secrets.CBCI_USERNAME }}
        token: ${{ secrets.CBCI_TOKEN }}
        job-name: "CloudBees_CI_job_name"
        test-type: JUnit/TestNG/GO
        test-result-location: junit-service*
        parameters: '{"BRANCH_NAME":"main","ENV_NAME":"stage"}'

----

In the following example, output is passed from {CI} to the platform.

The jenkinsfile below is used to define the outputs:

[source,groovy,role="default-expanded"]
----
node {
    stage('Build') {
        env.BUILD_NUMBER="1"
        env.TESTVAR="Test"
    }
}
----

The platform workflow file below prints the `BUILD_NUMBER` and `TESTVAR` outputs from {CI}:

[source,yaml,role="default-expanded"]
----
jobs:
  CBCI-Output-Job:
    outputs:
      cbci_output: ${{ steps.my-output-job.outputs.cbci_output }}
    steps:
      - id: my-output-job
        name: Run CBCI Job
        uses: cloudbees-io/cbci-run-job@v2
        with:
          url: ${{ vars.CBCI_URL }}
          username: ${{ secrets.CBCI_USERNAME }}
          token: ${{ secrets.CBCI_TOKEN }}
          job-name: cbci_job_with_output_name

      - id: expose-output-cbci
        name: Expose CBCI job output
        uses: docker://exozet/jq:1.6-r0
        run: |
          echo "BUILD_NUMBER: ${{ fromJSON(steps.my-output-job.outputs.cbci_output).BUILD_NUMBER }}"
          echo "TESTVAR: ${{ fromJSON(steps.my-output-job.outputs.cbci_output).TESTVAR }}"

  Print-CBCI-Outputs:
    needs: [CBCI-Output-Job]
    steps:
      - id: print-cbci-output
        uses: docker://exozet/jq:1.6-r0
        name: Print CBCI-Output-Job outputs
        run: |
          echo "BUILD_NUMBER: ${{ fromJSON(needs.CBCI-Output-Job.outputs.cbci_output).BUILD_NUMBER }}"
          echo "TESTVAR: ${{ fromJSON(needs.CBCI-Output-Job.outputs.cbci_output).TESTVAR }}"
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
